language: python

language: python
python:
  - "2.7"
  - "3.4"
#  - "3.6"
# command to install dependencies
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - pip install -r test_requirements.txt
  - pip install .
# command to run tests
script:
  - pytest
  - flake8
after_success:
  - coveralls
