language: python

language: python
python:
  - "2.7"
  - "3.4"
#  - "3.6"
# command to install dependencies
install:
  - pip install pytest matplotlib .
# command to run tests
script:
  - pytest
  - flake8
after_success:
  - coveralls
